### ISSUE TITLE
Codegen is not running

### ISSUE THREAD

**Issue by atakancosar** [vert-x3/vertx-guide-for-java-devs#4] opened 2017-06-19 14:11 UTC
I executed redeploy.sh, step1 and step2 is working but from step3 is not working.
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/atakan/Downloads/vertx-guide-for-java-devs-master/step-3 "-Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=51815:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2017.1.4 org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile
objc[2096]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x100e224c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x100ef04e0). One of the two will be used. Which one is undefined.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building wiki-step-3 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-cli) @ wiki-step-3 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /Users/atakan/Downloads/vertx-guide-for-java-devs-master/step-3/target/classes
Haz 19, 2017 4:58:58 PM io.vertx.codegen.CodeGenProcessor getCodeGenerators
WARNING: Please use 'codegen.output' option instead of 'outputDirectory' option
Haz 19, 2017 4:58:58 PM io.vertx.codegen.CodeGenProcessor lambda$getCodeGenerators$2
INFO: Loaded data_object_converters code generator
Haz 19, 2017 4:58:58 PM io.vertx.codegen.CodeGenProcessor lambda$getCodeGenerators$2
INFO: Loaded service_proxies code generator
Haz 19, 2017 4:58:59 PM io.vertx.codegen.CodeGenProcessor lambda$getCodeGenerators$2
INFO: Loaded service_proxies code generator
Haz 19, 2017 4:58:59 PM io.vertx.codegen.CodeGenProcessor lambda$getCodeGenerators$2
INFO: Loaded JavaScript code generator
Haz 19, 2017 4:58:59 PM io.vertx.codegen.CodeGenProcessor lambda$getCodeGenerators$2
INFO: Loaded cheatsheet code generator
Haz 19, 2017 4:58:59 PM io.vertx.codegen.CodeGenProcessor lambda$getCodeGenerators$2
INFO: Loaded cheatsheet code generator
Haz 19, 2017 4:58:59 PM io.vertx.codegen.CodeGenProcessor reportException
SEVERE: Could not generate element for io.vertx.guides.wiki.database.WikiDatabaseService: null
java.lang.NullPointerException
	at io.vertx.codegen.ProxyModel.checkParamType(ProxyModel.java:59)
	at io.vertx.codegen.ClassModel.getParams(ClassModel.java:920)
	at io.vertx.codegen.ClassModel.addMethod(ClassModel.java:769)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.vertx.codegen.ClassModel.traverseElem(ClassModel.java:627)
	at io.vertx.codegen.ClassModel.process(ClassModel.java:538)
	at io.vertx.codegen.CodeGen.getProxyModel(CodeGen.java:218)
	at io.vertx.codegen.CodeGen.lambda$null$17(CodeGen.java:141)
	at io.vertx.codegen.CodeGen$ModelEntry.getValue(CodeGen.java:106)
	at io.vertx.codegen.CodeGen$ModelEntry.getValue(CodeGen.java:88)
	at io.vertx.codegen.CodeGenProcessor.lambda$process$5(CodeGenProcessor.java:204)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.vertx.codegen.CodeGenProcessor.process(CodeGenProcessor.java:202)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/atakan/Downloads/vertx-guide-for-java-devs-master/step-3/src/main/java/io/vertx/guides/wiki/database/WikiDatabaseService.java:[36,8] Could not generate element for io.vertx.guides.wiki.database.WikiDatabaseService: null
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.937 s
[INFO] Finished at: 2017-06-19T16:58:59+03:00
[INFO] Final Memory: 22M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-cli) on project wiki-step-3: Compilation failure
[ERROR] /Users/atakan/Downloads/vertx-guide-for-java-devs-master/step-3/src/main/java/io/vertx/guides/wiki/database/WikiDatabaseService.java:[36,8] Could not generate element for io.vertx.guides.wiki.database.WikiDatabaseService: null
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1
```

**Comment by jponge** [comment] 2017-06-19 14:31
Hi @atakancosar,

Sadly _"it works for me"_...

Does ` mvn clean package` work for you?

**Comment by atakancosar** [comment] 2017-06-19 14:37
Hi @jponge 

`mvn clean package` does not work. It produce same result.

```SEVERE: Could not generate element for io.vertx.guides.wiki.database.WikiDatabaseService: null
java.lang.NullPointerException
```

**Comment by jponge** [comment] 2017-06-19 14:41
I can't reproduce that error.

Can you please update to the latest `master`? (I bumped to Vert.x 3.4.2)

**Comment by jponge** [comment] 2017-06-29 20:08
@atakancosar Do you still encounter the issue or can we close it?

**Comment by rdruss** [comment] 2017-07-03 04:27
Just pulled the repo and ran step-1 through step-3 and it works for me as well.

**Comment by fpmk** [comment] 2017-07-09 05:36
Hi everybody, I have similar issue, when I moved from vertx 3.4.1 to 3.4.2, proxygen fails

`Could not generate element for com.novice.proxyapi.transport.object.ProxyDealSpread: null
java.lang.UnsupportedOperationException
	at java.util.AbstractCollection.add(AbstractCollection.java:262)
	at io.vertx.codegen.DataObjectModel.lambda$processMethods$7(DataObjectModel.java:324)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.vertx.codegen.DataObjectModel.processMethods(DataObjectModel.java:324)
	at io.vertx.codegen.DataObjectModel.traverse(DataObjectModel.java:217)
	at io.vertx.codegen.DataObjectModel.process(DataObjectModel.java:154)
	at io.vertx.codegen.CodeGen.getDataObjectModel(CodeGen.java:184)
	at io.vertx.codegen.CodeGen.lambda$null$15(CodeGen.java:112)
	at io.vertx.codegen.CodeGen$ModelEntry.getValue(CodeGen.java:218)
	at io.vertx.codegen.CodeGen$ModelEntry.getValue(CodeGen.java:200)
	at io.vertx.codegen.CodeGenProcessor.lambda$process$5(CodeGenProcessor.java:204)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.vertx.codegen.CodeGenProcessor.process(CodeGenProcessor.java:202)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)`

**Comment by jponge** [comment] 2017-07-17 19:33
Closing the issue, seems like the +1 emoji was a _"Ok, works now"_ 😉

**Closed by jponge** 2017-07-17 19:33 UTC
